[package]
name = "deflestream64"
version = "0.1.0"
authors = ["Maxwell Beck <max@ryt.one>"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1"
argh = "0.1"
byteorder = "1"
tempfile = "3"

[build-dependencies]
cc = "1"
