name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86_64]

    steps:
      - uses: actions/checkout@v2
      - name: Install cc65 [Linux]
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install cc65
      - name: Install cc65 [macOS]
        if: matrix.os == 'macos-latest'
        run: brew install cc65
      - name: Install cc65 [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          curl -L "https://sourceforge.net/projects/cc65/files/cc65-snapshot-win32.zip/download" > cc65.zip
          unzip cc65.zip
        shell: bash
          
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo build --release
      - name: Upload Artifact [Non-Windows]
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v1
        with:
          name: deflestream64-${{ matrix.os }}
          path: target/${{ matrix.target }}/release/deflestream64
      - name: Upload Artifact [Windows]
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v1
        with:
          name: deflestream64-${{ matrix.os }}
          path: target/${{ matrix.target }}/release/deflestream64.exe
